# Header
logo: /img/arenda-vikup-bmw-moskva-oblast-podmoskove-logo.svg

# Miscellaneous
favicon: /favicon.ico
apple_touch_icon: /apple-touch-icon.png

# Social
facebook_url: 
instagram_url: 
twitter_url: 
email: 
formcarry_url: 