# Header
logo: /img/arenda-vikup-bmw-moskva-oblast-podmoskove-logo.svg

# Default Meta
title: Аренда и выкуп БМВ в Москве и Области
description: Аренда под такси и выкуп автомобилей БМВ в Москве и Московской области. Низкая стоимость (дешево 3700р в день). Полное страхование КАСКО. Бесплатное техническое обслуживание.

# Miscellaneous
favicon: /favicon.ico
apple_touch_icon: /apple-touch-icon.png

# Social
facebook_url: 
instagram_url: 
twitter_url: 
email: "&#105;&#110;f%6f%40b&#105;%6dme%72st%69&#99;k%65r.%73tor%65"
formcarry_url: 